java_library(
    name = "grakn-protocol",
    exports = [
        "//external:jar/io/grakn/protocol/grakn-protocol"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/com/google/protobuf:protobuf-java",
        "//dependencies/maven/artifacts/io/grpc:grpc-core",
        "//dependencies/maven/artifacts/io/grpc:grpc-protobuf",
        "//dependencies/maven/artifacts/io/grpc:grpc-stub"
    ],
    visibility = [
        "//visibility:public"
    ]
)


