java_library(
    name = "grakn-common",
    exports = [
        "//external:jar/io/grakn/common/grakn-common"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


