java_library(
    name = "antlr4-runtime",
    exports = [
        "//external:jar/org/antlr/antlr4-runtime"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


